sonar.organization=d3rpapah0d3n
sonar.projectKey=D3rPaPaH0d3n_eStundnzettl
sonar.projectName=eStundnzettl

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*.test.*,src/**/*.test.*
sonar.exclusions=src/**/__tests__/**,src/**/*.test.*,src/test/**,src/**/*.d.ts,src/**/*.json,src/**/*.md,src/**/*.css,src/locales/**,src/i18n/locales/**,src/i18n/TRANSLATION_STATUS.md

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
